// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9OqtT_Q3SQIFtl9KFN1swGnBEVBO3mY',
    appId: '1:48040700228:web:024d281612649b0d5d4f11',
    messagingSenderId: '48040700228',
    projectId: 'pacemeter-474b0',
    authDomain: 'pacemeter-474b0.firebaseapp.com',
    storageBucket: 'pacemeter-474b0.appspot.com',
    measurementId: 'G-ZVTNX6YZLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Z_FMONuTZcG6c_HPqBb0I000sGfbe3U',
    appId: '1:48040700228:android:fc2c57f7106c85f85d4f11',
    messagingSenderId: '48040700228',
    projectId: 'pacemeter-474b0',
    storageBucket: 'pacemeter-474b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEqv0_ZnPYKt19fORX1ete7Ul5UPsDPis',
    appId: '1:48040700228:ios:e0a26d8ca3e2ed185d4f11',
    messagingSenderId: '48040700228',
    projectId: 'pacemeter-474b0',
    storageBucket: 'pacemeter-474b0.appspot.com',
    androidClientId: '48040700228-h175vfnm19brto8b48sbjrmjt8rfaliq.apps.googleusercontent.com',
    iosClientId: '48040700228-nvudpbvh5d7rptk2vrkj47b43g7gua2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.radz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEqv0_ZnPYKt19fORX1ete7Ul5UPsDPis',
    appId: '1:48040700228:ios:e0a26d8ca3e2ed185d4f11',
    messagingSenderId: '48040700228',
    projectId: 'pacemeter-474b0',
    storageBucket: 'pacemeter-474b0.appspot.com',
    androidClientId: '48040700228-h175vfnm19brto8b48sbjrmjt8rfaliq.apps.googleusercontent.com',
    iosClientId: '48040700228-nvudpbvh5d7rptk2vrkj47b43g7gua2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.radz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8SVHPg_P9mMU1ZFy-MbQx-Hx-3aQwIjQ',
    appId: '1:48040700228:web:617c36f792d9b6bb5d4f11',
    messagingSenderId: '48040700228',
    projectId: 'pacemeter-474b0',
    authDomain: 'pacemeter-474b0.firebaseapp.com',
    storageBucket: 'pacemeter-474b0.appspot.com',
    measurementId: 'G-FXGY1SXY0H',
  );
}
